#! /bin/sh

### BEGIN INIT INFO
# Provides:          pimmer
# Required-Start:    $local_fs $network $remote_fs
# Required-Stop:     $local_fs $network $remote_fs
# Should-Start:      $NetworkManager
# Should-Stop:       $NetworkManager
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts instance of Pimmer
# Description:       starts instance of Pimmer using start-stop-daemon
### END INIT INFO

. /lib/lsb/init-functions

# Script name
NAME=pimmer

# App name
DESC=Pimmer

RUN_AS=pi

APP_PATH=/home/pi/pimmer

# Path to store PID file
PID_FILE=/var/run/pimmer.pid

# path to python bin
DAEMON=/usr/bin/python

# Extra start-stop-daemon option like START_OPTS=" --group=users"
EXTRA_SSD_OPTS=


PID_PATH=`dirname $PID_FILE`
DAEMON_OPTS=" pimmer.py --quiet --daemon --pid_file=${PID_FILE}"


test -x $DAEMON || exit 0

set -e

# Create PID directory if not exist and ensure the user can write to it
if [ ! -d $PID_PATH ]; then
    mkdir -p $PID_PATH
    chown $RUN_AS $PID_PATH
fi

if [ ! -d $DATA_DIR ]; then
    mkdir -p $DATA_DIR
    chown $RUN_AS $DATA_DIR
fi

if [ -e $PID_FILE ]; then
    PID=`cat $PID_FILE`
    if ! kill -0 $PID > /dev/null 2>&1; then
        echo "Removing stale $PID_FILE"
        rm $PID_FILE
    fi
fi

case "$1" in
  start)
        echo "Starting $DESC"
        start-stop-daemon -d $APP_PATH -c $RUN_AS $EXTRA_SSD_OPTS --start --pidfile $PID_FILE --exec $DAEMON -- $DAEMON_OPTS
        ;;
  stop)
        echo "Stopping $DESC"
        start-stop-daemon --stop --pidfile $PID_FILE --retry 15
        ;;

  restart|force-reload)
        echo "Restarting $DESC"
        start-stop-daemon --stop --pidfile $PID_FILE --retry 15
        start-stop-daemon -d $APP_PATH -c $RUN_AS $EXTRA_SSD_OPTS --start --pidfile $PID_FILE --exec $DAEMON -- $DAEMON_OPTS
        ;;

  status)
       status_of_proc -p $PID_FILE "$DAEMON" "$NAME"
        ;;
  *)
        N=/etc/init.d/$NAME
        echo "Usage: $N {start|stop|restart|force-reload|status}" >&2
        exit 1
        ;;
esac

exit 0